import type { Broadcaster } from "./broadcaster";

export interface Env {
	DB: D1Database;
	BROADCASTER: DurableObjectNamespace<Broadcaster>;
	STREAM_JWT_SECRET: string;
	WEBHOOK_SIGNING_SECRET: string;
	SHARD_COUNT: string;
}

/**
 * The shape of a single R2 event notification as delivered to the queue.
 * See https://developers.cloudflare.com/r2/buckets/event-notifications/
 */
export interface R2EventMessage {
	account: string;
	bucket: string;
	object: {
		key: string;
		size?: number;
		eTag?: string;
	};
	action:
		| "PutObject"
		| "CopyObject"
		| "CompleteMultipartUpload"
		| "DeleteObject"
		| "LifecycleDeletion";
	eventTime: string;
}

export interface FeedEvent {
	id: string; // Unique per delivery — generated by fanout
	bucket: string;
	key: string;
	action: string;
	size?: number;
	etag?: string;
	event_time: string;
}
